long lines hook

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -15,3 +15,27 @@ else
 	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
+
+# Detect too long lines in .php and .html files:
+changed_source_files=`git diff-index --cached $against --numstat |
+cut -f3 |
+egrep '\.[php html]$'`
+ 
+if [[ -n "$changed_source_files" ]]; then
+found_offenses=''
+ 
+for file in $changed_source_files ; do
+too_long=`git diff-index --cached -p $against -- "$file" |
+egrep '^\+.{117,}' |
+sed -E 's/^\+//'`
+if [[ -n "$too_long" ]]; then
+found_offenses=YES
+printf "\n$file:\n%s\n" "$too_long" >&2
+fi
+done
+ 
+if [[ -n $found_offenses ]]; then
+echo "\nAborting commit because you added lines longer than 116 chars." >&2
+exit 1
+fi
+fi
